[package]
id = "inputlagvisualisatidmrkbzo4qmbou"
name = "Input Lag Visualisation"
version = "0.0.1"
content = { type = "Playable" }
ambient_version = "0.3.0"

[dependencies]
frame_time = { path = "../measure/frame_time" , deployment = "ZBBwVcY1aGwvX2Y4kXUgQ" }
input_lag = { path = "../measure/input_lag" , deployment = "6QCMD5hZe23eE5lb2EdaDY" }

[components]
delay = { type = "U32", name = "millis artificially added to frame processing on the client", attributes = ["Debuggable"] }
x_translation = { type = "F32", name = "X translation of player's square", attributes = ["Debuggable", "Networked"] }
visibility = { type = "U8", name = "Square visibility flags", attributes = ["Debuggable"] }

[messages.Input.fields]
direction = "F32"
